### PR TITLE
Adjusted Date Picker Logic

### LINKED ISSUE #19: Enhance the ui and logic behind start date and end date
### Propose changes
- Enhance the start date and end date ui and add a logic which will not allow one to select a date which is less than the start date.
- Change the react logic behind the date
image
we want something like this:
image

### PR DESCRIPTION
**Pull request by alexsam29**
This PR is intended to resolve #19.

I kept the same date picker component as before, but removed one of the date picker fields.  So now there is only one field which will show a date range. 

When a user selects a date, that date will be used as the `startDate`.  The second selection will then be used as the `endDate`. If the user attempts a third selection, the process will start over and that date will be used for the `startDate` and so on.

I added then removed max and min date restrictions because should a user select an `endDate` that is before the `startDate`, that date will be used as the `startDate` instead.

CSS/UI could use some adjustment since there is only one date picker now, but I ran into some troubles.  That could be a whole other issue.

## Code Changes
- Added state hooks to set `startDate` and `endDate`.
- Added `onChange` function to set `startDate` and `endDate`.
- Adjusted `onChange` attribute within `<DatePicker/>` to handle date selection.
- Added attributes within `<DatePicker/>` to show the range selected and to add year & month dropdown selection.
- Renamed `Date` label to `Date Range` to indicate that's two dates need to be selected.
- Adjusted CSS to widen date input field.

### CODE REVIEW

**Comment by Dhruv031003** [comment]
@alexsam29 
Happy belated Deepawali🎉🎊🔮🥳
Sorry for the late response, was busy celebrating.
Great work.

# Issues
- Please change the date format to DD-MM-YYYY 
- When we select same date for start and end date it doesn't show any results, this can be an issue with the backend. Just check if everthing's fine in the forntend or not.(It was already there but discovered it while checking your PR).
- Either remove the feature of typing date, or user should be able to enter numbers only and that too in a fixed DD-MM-YYYY format only.
image
<hr>
CSS/UI issues will be fixed in seperate issues later.

**Comment by alexsam29** [comment]
### Additional Changes 
- Date format changed to DD/MM/YYYY
- User cannot type anything into the input field. Date must be selected from the dropdown calendar.

I also get the same bug when I select the same day as the start and end date.  But everything in the front-end seems to be correct as the same value appears for both start and end dates  

image

**Comment by Dhruv031003** [comment]
@alexsam29 

Issue
- It loads new tweets as soon as we select `startDate`, when we select the `endDate` it sends new request and loads the tweets again. This should not happen it should wait for the user to select both and then load new tweets.
- We can select date greater than current date.

**Comment by alexsam29** [comment]
Those issues have been addressed.  Hopefully now everything works alright.

**Comment by Dhruv031003** [comment]
@alexsam29 
Yup everything's good now.
Please solve the merge conflicts, then we can close this PR.

**Comment by Dhruv031003** [comment]
@alexsam29 
image
The build is failing because of these unused var.

**Comment by Dhruv031003** [comment]
@alexsam29 
Thanks for the Contribution.

**Pull request merged**
