### PR TITLE
improved loading screen

### PR DESCRIPTION
**Pull request by REX-HERE**
#10  replaced the icon with a [better one](https://64.media.tumblr.com/9120a4251f6f70b28276787654fa72ac/tumblr_n2pixn4IlF1rjledmo1_500.gifv) -

loading_ani

### CODE REVIEW

**Comment by mr-palindrome** [comment]
Hey @REX-HERE!
This looks really great! But can you add something which is similar to the old one, but much bigger.
Something like this (but in black with grey gradient color):
image
Take reference form this https://www.google.com/url?sa=i&url=https%3A%2F%2Fuxplanet.org%2Fusing-loading-animation-on-websites-and-apps-examples-and-snippets-to-use-cab0097be9f1&psig=AOvVaw2W-lbduzX53PhG6gOajsRX&ust=1665463827148000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCPif-7Du1PoCFQAAAAAdAAAAABAE

**Comment by REX-HERE** [comment]
> Hey @REX-HERE! This looks really great! But can you add something which is similar to the old one, but much bigger. Something like this (but in black with grey gradient color): image Take reference form this https://www.google.com/url?sa=i&url=https%3A%2F%2Fuxplanet.org%2Fusing-loading-animation-on-websites-and-apps-examples-and-snippets-to-use-cab0097be9f1&psig=AOvVaw2W-lbduzX53PhG6gOajsRX&ust=1665463827148000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCPif-7Du1PoCFQAAAAAdAAAAABAE

there are very few good designs in black-grey line type but i will try to find some.

**Comment by mr-palindrome** [comment]
> > Hey @REX-HERE! This looks really great! But can you add something which is similar to the old one, but much bigger. Something like this (but in black with grey gradient color): image Take reference form this https://www.google.com/url?sa=i&url=https%3A%2F%2Fuxplanet.org%2Fusing-loading-animation-on-websites-and-apps-examples-and-snippets-to-use-cab0097be9f1&psig=AOvVaw2W-lbduzX53PhG6gOajsRX&ust=1665463827148000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCPif-7Du1PoCFQAAAAAdAAAAABAE
> 
> there are very few good designs in black-grey line type but i will try to find some.

Or you can add a gif of black dot loading in circular motion.

**Comment by REX-HERE** [comment]
#10 loading screen improved, and changes are made in the development branch
loading_circle

**Review by mr-palindrome — APPROVED** [review]

**Comment by mr-palindrome** [comment]
Hey @REX-HERE  I reverted the changes!
as there were two loading gif at a time!
image
image

Please fix this and create a new PR

**Pull request merged**
