### PR TITLE
feat: improve selection

### LINKED ISSUE #9: More selection required.
Currently this selection has only few limited fields.
But we need more such fields like Java, Spring, MERN, NodeJS, etc.
image

### PR DESCRIPTION
**Pull request by photon0205**
Resolved #9

### CODE REVIEW

**Comment by mr-palindrome** [comment]
Hey @photon0205!
Can you add few more input values, as I mentioned in the issue #9 you can take reference form the gihtub trending page.

**Comment by photon0205** [comment]
> Hey @photon0205!
> Can you add few more input values, as I mentioned in the issue #9 you can take reference form the gihtub trending page.

ohhkk, I thought that was the reference for a proper layout, alright then I am adding some more input values

**Comment by Dhruv031003** [comment]
@photon0205 can you please mention what extra packages you installed.

**Comment by photon0205** [comment]
> @photon0205 can you please mention what extra packages you installed.
The extra packages I installed are mentioned in the changes in package.json file. You can use `npm install` or `npm I` to install all those packages. Nevertheless here are the packages I installed:
     "@emotion/react": "^11.10.4"             
     "@emotion/styled": "^11.10.4"                      
     "@mui/icons-material": "^5.10.6"
     "@mui/material": "^5.10.8"
     "@mui/styled-engine-sc": "^5.10.6"
     "styled-components": "^5.3.6"
you can use 
`npm install @mui/material @emotion/react @emotion/styled @mui/icons-material @mui/styled-engine-sc styled-components` 
to install all the mentioned packages in one go

**Comment by photon0205** [comment]
> @photon0205 can you please mention what extra packages you installed.

The extra packages I installed are mentioned in the changes in package.json file. You can use `npm install` or `npm i` to install all those packages. Nevertheless here are the packages I installed:

- "@emotion/react": "^11.10.4"
- "@emotion/styled": "^11.10.4"
- "@mui/icons-material": "^5.10.6"
- "@mui/material": "^5.10.8"
- "@mui/styled-engine-sc": "^5.10.6"
- "styled-components": "^5.3.6"

you can use
`npm install @mui/material @emotion/react @emotion/styled @mui/icons-material @mui/styled-engine-sc styled-components`
to install all the mentioned packages in one go

**Comment by Dhruv031003** [comment]
There are multiple issues with your code.

### Issues
- When changing the values it's giving two elements with same key error.
- When the value input is not available in the list it still reloads the page this should not happen it should only allow user to select values from the list.

### Enhancements
- Please remove list items which are larger than 2-3 words.
- When page reloads first time it should show the default topic i.e. reactJs.

**Review by Dhruv031003 — CHANGES_REQUESTED** [review]
I requested some changes before merging it

**Comment by photon0205** [comment]
@Dhruv031003 I have fixed all the issues and enhanced the code as you requested. I hope #24 now resolves all the issues. You can review it now

**Comment by Dhruv031003** [comment]
@photon0205 
image
### Issues
- If we change the value without clearing the field first it doesn't change the value. To change it we have to clear the field using cross then change it.

**Comment by photon0205** [comment]
@Dhruv031003 I have improved the code. You can review

**Comment by Dhruv031003** [comment]
> There are multiple issues with your code.
> 
> ### Issues
> * When changing the values it's giving two elements with same key error.
> * When the value input is not available in the list it still reloads the page this should not happen it should only allow user to select values from the list.
> 
> ### Enhancements
> * Please remove list items which are larger than 2-3 words.
> * When page reloads first time it should show the default topic i.e. reactJs.

@photon0205 
- The second issue still persists. 
Can you fix it or do you need help in it??

**Comment by photon0205** [comment]
@Dhruv031003 , sry actually I misinterpreted what you wanted to say, now I have corrected the code. You can review

**Comment by Dhruv031003** [comment]
@photon0205
Evething's fine, All the issues are resolved now. 
Thanks for your contribution Great Work there!!!

I am merging this PR now.

**Comment by photon0205** [comment]
This is my first proper open source contribution, I had fun doing it.

**Comment by Dhruv031003** [comment]
You did great as a first timer. 😵‍💫
Keep up the good work and keep contributing.😊

**Pull request merged**
