### PR TITLE
There is no master branch for this repo. Fixes in contributing.md. Code optimization for topics. Add more topics.

### PR DESCRIPTION
**Pull request by nirajpdn**

### CODE REVIEW

**Comment by mr-palindrome** [comment]
Hey @nirajpdn!
I think this is related to issue #9!
I think you have read the README.md where it is written "Do not make a PR without getting the issues assigned".
So first get it assigned first!

**Comment by nirajpdn** [comment]
@mr-palindrome I didn't see any issues related to contributing.md with the branch name. There is master branch mentioned but the repo don't contain master branch. 
 I have optimized the code little bit for topics rather than design.

**Comment by mr-palindrome** [comment]
> @mr-palindrome I didn't see any issues related to contributing.md with the branch name. There is master branch mentioned but the repo don't contain master branch.
> I have optimized the code little bit for topics rather than design.

Still for this you need to create an issue first and get it assigned!

**Comment by mr-palindrome** [comment]
For now I'm closing this PR you can create a new PR after creating a issue related to contribution.md

**Pull request closed without merging**
