### PR TITLE
All UI update

### PR DESCRIPTION
**Pull request by photon0205**
Updated the UI as demanded by the issue #33

### CODE REVIEW

**Comment by photon0205** [comment]
@Dhruv031003 now is it good?
Also will you create a new issue for the changes in ui of the rest of the page other than the Navbar so that I can make one more contribution to Hacktoberfest 😅 😜 😜

**Comment by photon0205** [comment]
I have also found a work around for that margin at the top of the twitter embed. Will implement it too in the new issue (if created)

**Comment by Dhruv031003** [comment]
@photon0205 
image
Please fix this.
- Either make it like the UI or change it back to how it was earlier.

**Comment by Dhruv031003** [comment]
> @Dhruv031003 now is it good? Also will you create a new issue for the changes in ui of the rest of the page other than the Navbar so that I can make one more contribution to Hacktoberfest 😅 😜 😜

- You have already updated the whole ui.
- I can see multiple improvements that can be made in your PR, I will create seperate issues for them so you can complete your PR's for Hacktoberfest.

**Comment by Dhruv031003** [comment]
> I have also found a work around for that margin at the top of the twitter embed. Will implement it too in the new issue (if created)

Okay I will create it after merging your PR, first fix the issues mentioned above.

**Comment by photon0205** [comment]
Now is it alright @Dhruv031003

**Comment by Dhruv031003** [comment]
@photon0205 
Yup everything looks fine.
I am merging it. 
- There are some improvements that can be made in this, I will create seperate issues for them you can revert on them.

**Pull request merged**
