### PR TITLE
Reduced the margins

### PR DESCRIPTION
**Pull request by photon0205**
Does this solved the issue #44 @Dhruv031003 ?

### CODE REVIEW

**Comment by Dhruv031003** [comment]
@photon0205 
Happy Belated Deepawali.
Sorry for the late reply.
Yup the issue is fixed now. I am merging this.

**Comment by Dhruv031003** [comment]
Have you completed your PR's for hacktoberfest?
Which PR you would you like to be merged first??

**Comment by photon0205** [comment]
Yes @Dhruv031003, thanks to you I have completed my Hacktoberfest PRs. It has been amazing working with you.
And you can merge any of the PR first as I have worked on both independently.

**Comment by photon0205** [comment]
Also @Dhruv031003 Happy Diwali from my side as well

**Pull request merged**
