### PR TITLE
#28 handle empty response

### LINKED ISSUE #28: Api Response Empty
- When response from Api is empty it shows blank screen.
- Display a message telling that there are no search results.

### PR DESCRIPTION
**Pull request by ozair-dev**
I have added the text for when the response is empty. Plus I have done some code refactoring as I noticed that the logic was poorly coded. Please review the PR.
Screenshot from 2022-10-12 21-06-47

Fixed #28

### CODE REVIEW

**Comment by Dhruv031003** [comment]
@ozair-dev 
Thanks for the code refactoring but there are multiple issues.

image
image
- These loaders should be in the middle horizontally.

- If page is reloaded before the tweets load or while new tweets are being loaded it shows the alert, if possible remove it or just console log the error.

- If we go to the end of any page i.e. if there are no more tweets left and then you change any input value it shows "Your search did not return any results" and then after some time loads the new tweets.

**Review by Dhruv031003 — CHANGES_REQUESTED** [review]
Some changes are requested.

**Comment by ozair-dev** [comment]
- [x] If page is reloaded before the tweets load or while new tweets are being loaded it shows the alert, if possible remove it or just console log the error
- [x] If we go to the end of any page i.e. if there are no more tweets left and then you change any input value it shows "Your search did not return any results" and then after some time loads the new tweets.

> These loaders should be in the middle horizontally.

I already set the loader in the middle in my last commit. I rechecked it and it is working fine on my machine. You can also see my changes in the **Spinner** component. If you still see the issue then I want you deploye my changes to production and I'll see for myself what the issue is.
Screenshot from 2022-10-13 20-46-47

**Comment by Dhruv031003** [comment]
@ozair-dev 
> * [x]  If page is reloaded before the tweets load or while new tweets are being loaded it shows the alert, if possible remove it or just console log the error
> * [x]  If we go to the end of any page i.e. if there are no more tweets left and then you change any input value it shows "Your search did not return any results" and then after some time loads the new tweets.
> 
> > These loaders should be in the middle horizontally.
> 
> I already set the loader in the middle in my last commit. I rechecked it and it is working fine on my machine. You can also see my changes in the **Spinner** component. If you still see the issue then I want you deploye my changes to production and I'll see for myself what the issue is. Screenshot from 2022-10-13 20-46-47

Okay, my bad i didn't view the code properly.
All the issues are fixed I am merging it.

Thanks for the contribution, Keep contributing, Keep growing 😊

**Pull request merged**
