### PR TITLE
UI Update

### PR DESCRIPTION
**Pull request by photon0205**
Updated the UI as demanded by the issue #33

### CODE REVIEW

**Comment by photon0205** [comment]
@Dhruv031003 , I just read that my work was just to update the UI of the Navbar, I also updated the UI of the rest of the page as it was in the figma link (as I was just following the link).

**Comment by photon0205** [comment]
If you want I can create a different branch with just the Navbar changes and you can create a new issue for the ui change of rest of the page

**Comment by Dhruv031003** [comment]
@photon0205 

You are using an older version of React which is creating issues with the site deployment.
- Please update your version and then commit the changes again.

**Comment by photon0205** [comment]
@Dhruv031003 actually there was not any problem with the version of react instead some packages were creating this issue, which I took care of in a new branch of which I have raised the pr

**Pull request closed without merging**
