### PR TITLE
Issue #25

### PR DESCRIPTION
**Pull request by salilgupta2510**
Changes: 

Removed multiple loaders appearing on the screen.
Added Error handling in API calls (Currently logging the error in the console, later can be modified with an UX).
Removed redundant code.

### CODE REVIEW

**Comment by Dhruv031003** [comment]
@salilgupta2510 
### Issues
- The whole twittercontainer component shakes continously.
https://user-images.githubusercontent.com/91516121/194944386-d6de5efc-6582-4a9a-a3db-b7c4085fd322.mp4
- fix this and revert 

### Tips
- Add some description while raising a PR for other's to better understand what you have done

**Comment by salilgupta2510** [comment]
@Dhruv031003 The issue has been addressed. Twitter container component renders as expected.

**Comment by Dhruv031003** [comment]
@salilgupta2510 You removed the spinner?

**Comment by salilgupta2510** [comment]
@Dhruv031003 yes, Nayan mentioned that someone else is already working on the spinner. So I can revert my code for the loader change I did. #25

**Comment by Dhruv031003** [comment]
Ohkay no issues.
Everthing's fine with your code i will merge it now.

**Pull request merged**
