### PR TITLE
Fix for calendar date change issue

### LINKED ISSUE #34: Calender date change
image

### Issue
- When any of these arrows are pressed the date updates which results in loading of new tweets.

This should not happen.
The date should change only when a particular date is selected form the calender rather than on clicking the arrows.

### PR DESCRIPTION
**Pull request by alexsam29**
This PR is intended to resolve #34. 

I could not solve this issue with the HTML date picker that is in use.  So, I used the React date picker component in place of the default HTML date picker.  I tried to keep it similar to the current method.

In my testing, the date does not change when the user uses the arrows to change the month.  Everything else appears to be working as normal.

Please let me know if there are any bugs or changes I should make.

## Changes/Additions
- Added `react-datepicker` package to make use of the [React Date Picker](https://www.npmjs.com/package/react-datepicker) component.
- Replaced the `<input>` field for both `startDate` and `endDate` with the `<DatePicker>` React Component.

### CODE REVIEW

**Comment by Dhruv031003** [comment]
@alexsam29 
### Issues
- If you select any date, the date which gets selected is 1 less than the selected date. This issue occurs with both date inputs.
- When the Start date dropdown opens it shifts the End date dropdown to the right(Happens with both inputs but is visible only with start date). It would be great if you fix this too.

I see no other issues with this for now.

**Comment by alexsam29** [comment]
I think I have fixed the movement issue.

The only problem now is that I can't recreate the date being less than selected.
image

On my end, when a date is selected, it's the correct date.  

In the image above I selected `2022-09-04` first for the start date, which is shown in the console output correctly. Then I selected `2022-10-12` for the end date, which is also shown in the console as correct.

**Comment by alexsam29** [comment]
Try this. I got rid of some code that makes the date on my end one more than selected.  So maybe it's correct on your end now.

**Comment by Dhruv031003** [comment]
@alexsam29 
Yes, now it's working fine.

**Comment by Dhruv031003** [comment]
I will make sure everthing's right and then I will merge it.

**Comment by Dhruv031003** [comment]
@alexsam29 

The issue is not with your code I guess it was with the backend. We will fix it asap, Sorry for inconvenience.

image
Here date selected is 14th but it's showing tweets from 13th.

image
Here date selected is 13th but it's showing tweets from 12th

I will be merging this PR now

**Comment by Dhruv031003** [comment]
Thanks for the contribution😇
Keep contributing, Keep growing.😇

**Pull request merged**
