### PR TITLE
Checkbox for WFH

### PR DESCRIPTION
**Pull request by photon0205**
Resolved the issue #35

### CODE REVIEW

**Comment by photon0205** [comment]
@Dhruv031003 Is it alright? You can review this.

**Comment by Dhruv031003** [comment]
@photon0205 
- Yes it's working properly, can you make it round it will look more appealing and elegant.

**Comment by photon0205** [comment]
I just replaced the checkbox with a radio-button. Will this do the work @Dhruv031003 ?

**Comment by Dhruv031003** [comment]
@photon0205 
Yes it's working fine.

**Pull request merged**
